In [1]:
import numpy as np

In [2]:
# converting list to numpy array
l=[1,2,3,4,5]
arr1=np.array(l)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
# ndmin= n-dimensional 1-D Array
arr1=np.array(l,ndmin=1)
print(type(arr1))
print(arr1)

# ndmin= n-dimensional 2-D Array
arr2=np.array(l,ndmin=2)
print(type(arr2))
print(arr2)

<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3 4 5]]


In [11]:
# creates an array from 1 to 9 with a gap of '1'
arr=np.arange(1,10,1)
print(arr)

# creates an array from 1 to 9 with a gap of '2'
arr=np.arange(1,10,2)
print(arr)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [13]:
# 'arr' is a 2-D Array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
# arr1 is a 1-D array
arr1=np.array([1,2,3,4,5,6,7])
print(arr1.size)

# arr2 is a 2-D array
arr2=np.array([[1,2,3,4],[2,3,4,5],[5,6,7,8]])
print(arr2.size)
print(np.size(arr2,0))    # '0' for row size
print(np.size(arr2,1))    # '1' for column size

7
12
3
4


In [19]:
# Data Type of the array
arr1=np.array([1,2,3,4,5,6,7])
print(arr1.dtype)

arr2=np.array([1.2,3.2,4.3,2.3])
print(arr2.dtype)

int32
float64


In [23]:
# Dimensions of the array
arr1=np.array([1,2,3,4,5,6,7])
print(arr1.ndim)

arr2=np.array([[1,2,3,4],[2,3,4,5],[5,6,7,8]])
print(arr2.ndim)

1
2


In [25]:
# creating arrays with all zeros

arr1=np.zeros((3,4))     # 2-D
print("Printing 2-D array: ")
print(arr1)

print("Printing 1-D array: ")
arr2=np.zeros(4)       # 1-D
print(arr2)

Printing 2-D array: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Printing 1-D array: 
[0. 0. 0. 0.]


In [26]:
# creating arrays with all ones

arr1=np.ones((3,4))     # 2-D
print("Printing 2-D array: ")
print(arr1)

print("Printing 1-D array: ")
arr2=np.ones(4)       # 1-D
print(arr2)

Printing 2-D array: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Printing 1-D array: 
[1. 1. 1. 1.]


In [28]:
# eye() is used to create Identity matrix
arr1=np.eye(4,dtype=int)
print(arr1)

arr2=np.eye(6,dtype=float)
print(arr2)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [58]:
# empty() returns an empty array with all elements as '0'
arr2=np.empty(shape=(3,4))
print(arr2)

[[0.29488109 0.24665191 0.34342049 0.00975786]
 [0.22595107 0.44140059 0.76422454 0.19697829]
 [0.06507297 0.64522439 0.96562745 0.80641561]]


In [43]:
# random.rand() is used to create an Array with random numbers between 0.0-1.0
arr1=np.random.rand(4)
print(arr1)

arr2=np.random.rand(3,4)
print(arr2)

[0.25388293 0.61422633 0.09741231 0.89845886]
[[0.29488109 0.24665191 0.34342049 0.00975786]
 [0.22595107 0.44140059 0.76422454 0.19697829]
 [0.06507297 0.64522439 0.96562745 0.80641561]]


In [47]:
# random.randint() creates an array of 'size' with random values between 'low' and 'high'
arr1=np.random.randint(low=1,high=11,size=10)
print(arr1)


[3 8 8 6 7 3 6 5 5 3]


In [49]:
# random.randn() creates an array of '15' with random values under Standard Normal Distribution
arr1=np.random.randn(15)
print(arr1)

[ 1.81821909 -0.56106847  1.42061076 -0.91497304  1.4029422   1.25904714
 -1.14145944 -0.82745011  0.02899114  1.52209522 -0.9235742  -0.11325818
 -0.01720296 -0.18604754  0.65264667]


In [56]:
# firstly we create an array of random integers of size(3*4), then reshaped it to size(4*3)
# note that the number of elements in the initial and final array should be same

arr1=np.random.randint(1,11,(3,4))
print("Printing initial array: ")
print(arr1)

arr2=arr.reshape(4,3)
print("Printing array after reshaping: ")
print(arr2)

Printing initial array: 
[[ 5  7  4 10]
 [10  6  6  3]
 [ 6  1  1  2]]
Printing array after reshaping: 
[[ 4  9  4]
 [ 3  9  6]
 [ 5  6  3]
 [ 6  2 10]]


In [66]:
# linspace() creates an array of '14' size from '1' to '10' with equal intervals
arr=np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [68]:
# flatten() convert any 'n' dimensional array to a 1-D array
arr1=np.array([[1,2,3,4],[2,3,4,5],[5,6,7,8]])
print("Printing original array: ")
print(arr1)
arr2=arr1.flatten()
print("Printing flattened array: ")
print(arr2)

Printing original array: 
[[1 2 3 4]
 [2 3 4 5]
 [5 6 7 8]]
Printing flattened array: 
[1 2 3 4 2 3 4 5 5 6 7 8]


In [70]:
# logspace() creates an array of '10' size from 'log(2)' to 'log(4)' with equal intervals (Default base is '10')
arr1=np.logspace(2,4,10)
print(arr1)

# creates an array of '10' size from 'log(2) base 2' to 'log(4) base 2' with equal intervals
arr2=np.logspace(2,4,10,base=2)
print(arr2)

[  100.           166.81005372   278.25594022   464.15888336
   774.26368268  1291.54966501  2154.43469003  3593.8136638
  5994.84250319 10000.        ]
[ 4.          4.66611616  5.44316     6.34960421  7.4069977   8.64047791
 10.0793684  11.75787594 13.71590373 16.        ]


In [75]:
# copying arrayd
arr1=np.random.randint(1,10,10)
print(arr1)
arr2=np.random.randint(1,20,10)
print(arr2)

# Simple copying ... same refrence to memory
# same i'd means both arrays point to the same memory
arr2=arr1
print(arr1,id(arr1))
print(arr2,id(arr2))
# using copy() function
# creates 2 different arrays in different memory locations... hence i'd is alsk different
arr2=np.copy(arr1)
print(arr1,id(arr1))
print(arr2,id(arr2))

[9 3 7 2 3 5 6 6 4 2]
[19  2 13 17 10  9 10  5  8 10]
[9 3 7 2 3 5 6 6 4 2] 3059097219984
[9 3 7 2 3 5 6 6 4 2] 3059097219984
[9 3 7 2 3 5 6 6 4 2] 3059097219984
[9 3 7 2 3 5 6 6 4 2] 3059087929584


In [88]:
# 1-D Array
print('-'*30)
arr1=np.random.randint(1,10,10)
print(arr1)
print('-'*30)
print("Maximum Element: ",arr1.max())
print("Minimum Element: ",arr1.min())
print("Sum of all Element: ",arr1.sum())
print('-'*30)

# 2-D Array... axis=0 for columns .....axis=1 for rows
arr2=np.random.randint(1,10,(3,4))
print(arr2)
print('-'*30)
print("Maximum Element: ",arr2.max())
print("Minimum Element: ",arr2.min())
print("Sum of all Element: ",arr2.sum())
print('-'*30)
print("Maximum Element ColumnWise: ",arr2.max(axis=0))
print("Minimum Element ColumnWise: ",arr2.min(axis=0))
print("Sum of all Element ColumnWise: ",arr2.sum(axis=0))
print('-'*30)
print("Maximum Element RowWise: ",arr2.max(axis=1))
print("Minimum Element RowWise: ",arr2.min(axis=1))
print("Sum of all Element RowWise: ",arr2.sum(axis=1))
print('-'*30)

------------------------------
[3 6 7 5 6 1 6 1 5 4]
------------------------------
Maximum Element:  7
Minimum Element:  1
Sum of all Element:  44
------------------------------
[[3 4 8 8]
 [3 5 3 9]
 [9 9 6 7]]
------------------------------
Maximum Element:  9
Minimum Element:  3
Sum of all Element:  74
------------------------------
Maximum Element ColumnWise:  [9 9 8 9]
Minimum Element ColumnWise:  [3 4 3 7]
Sum of all Element ColumnWise:  [15 18 17 24]
------------------------------
Maximum Element RowWise:  [8 9 9]
Minimum Element RowWise:  [3 3 6]
Sum of all Element RowWise:  [23 20 31]
------------------------------


In [94]:
# seed(valuw) .....generates pseudoRandom numbers which are not purely random (can be guessed)
# it generates same random integer array umtil the 'value' inside the seed() remains same
# seed() is very very important
np.random.seed(4)
arr=np.random.randint(1,10,10)
print(arr)

[8 6 2 9 8 9 3 8 8 8]


In [100]:
arr1=np.random.randint(1,10,10)
print("Printing unsorted array: ")
print(arr1)
print("Printing sorted array: ")
print(np.sort(arr1))
print(40*'-')

arr2=np.random.randint(1,10,(3,4))
print("Printing unsorted array: ")
print(arr2)
print("Printing sorted array: ")
print(np.sort(arr2))
print("Printing sorted array rowWise: ")
print(np.sort(arr2,axis=1))
print("Printing sorted array columnWise: ")
print(np.sort(arr2,axis=0,kind="mergesort"))

Printing unsorted array: 
[9 8 6 8 7 9 5 5 1 8]
Printing sorted array: 
[1 5 5 6 7 8 8 8 9 9]
----------------------------------------
Printing unsorted array: 
[[3 2 9 9]
 [2 4 2 4]
 [7 8 5 1]]
Printing sorted array: 
[[2 3 9 9]
 [2 2 4 4]
 [1 5 7 8]]
Printing sorted array rowWise: 
[[2 3 9 9]
 [2 2 4 4]
 [1 5 7 8]]
Printing sorted array columnWise: 
[[2 2 2 1]
 [3 4 5 4]
 [7 8 9 9]]


In [108]:
# Mathematical operations on arrays
np.random.seed(4)
arr=np.random.randint(1,10,(3,3))
print(40*'-')
print(arr)
print(40*'-')
print(arr+1)     # adding 1 to each element of array
print(40*'-')
print(arr-2)     # substracting 2 to each element of array
print(40*'-')
print(arr*3)     # multiplying by 3 to each element of array
print(40*'-')
print(arr/2)     # dividing by 2 to each element of array
print(40*'-')
print(arr//2)    # floor division by 2 to each element of array
print(40*'-')
print(arr**2)    # power of 2 to each element of array
print(40*'-')

----------------------------------------
[[8 6 2]
 [9 8 9]
 [3 8 8]]
----------------------------------------
[[ 9  7  3]
 [10  9 10]
 [ 4  9  9]]
----------------------------------------
[[6 4 0]
 [7 6 7]
 [1 6 6]]
----------------------------------------
[[24 18  6]
 [27 24 27]
 [ 9 24 24]]
----------------------------------------
[[4.  3.  1. ]
 [4.5 4.  4.5]
 [1.5 4.  4. ]]
----------------------------------------
[[4 3 1]
 [4 4 4]
 [1 4 4]]
----------------------------------------
[[64 36  4]
 [81 64 81]
 [ 9 64 64]]
----------------------------------------


In [169]:
# matrix multiplication (dot product)
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))
print(30*'-')
print(arr1)
print(30*'-')
print(arr2)
print(30*'-')
print(arr1.dot(arr2))
print(30*'-')
print(arr2.dot(arr1))
print(30*'-')

# '@ is also used for the dot product'
print(arr1@arr2)
print(30*'-')
print(arr2@arr1)
print(30*'-')

------------------------------
[[4 4 1]
 [8 7 2]
 [8 7 4]]
------------------------------
[[8 3 8]
 [9 2 3]
 [1 7 9]]
------------------------------
[[ 69  27  53]
 [129  52 103]
 [131  66 121]]
------------------------------
[[120 109  46]
 [ 76  71  25]
 [132 116  51]]
------------------------------
[[ 69  27  53]
 [129  52 103]
 [131  66 121]]
------------------------------
[[120 109  46]
 [ 76  71  25]
 [132 116  51]]
------------------------------


In [118]:
# percentile('array','out of how much') 
np.random.seed(4)
marks=np.random.randint(50,100,10)
print(marks)
marks=np.sort(arr)
print(marks)
print(np.percentile(arr,50))

[96 55 51 90 73 58 59 89 95 80]
[51 55 58 59 73 80 89 90 95 96]
76.5


In [121]:
np.random.seed(4)
arr=np.random.randint(1,10,10)
print("Array: ",arr)
print("Mean: ",np.mean(arr))   # mean
print("Mean: ",np.var(arr))    # variance
print("Mean: ",np.std(arr))    # standard deviation

Array:  [8 6 2 9 8 9 3 8 8 8]
Mean:  6.9
Mean:  5.49
Mean:  2.3430749027719964


In [125]:
# filtering an array
arr=np.arange(1,10)
print(arr)
print(arr>5)
print(arr[arr>5])

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
[6 7 8 9]


In [131]:
# replacing all values greater than '5' with '10'
arr=np.arange(1,10)
print(arr)
arr[arr>5]=10
print(arr)

[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5 10 10 10 10]


In [137]:
# transpose of a matrix (arr.T)
np.random.seed(4)
arr=np.random.randint(1,10,10)
print("Original Matrix: \n",arr)
print("Transposed Matrix: \n",arr.T)

Original Matrix: 
 [8 6 2 9 8 9 3 8 8 8]
Transposed Matrix: 
 [8 6 2 9 8 9 3 8 8 8]


In [145]:
# where() is also a filter function which filters/replaces values according to the given condition
# where('condition','replace with','array')

np.random.seed(4)
arr=np.random.randint(1,10,10)
print(50*'-')
print(np.where(arr%2==0,100,arr))    # replace all even values with 100 in the array
print(50*'-')
print(np.where(arr%2==0,"Even",arr))
print(np.where(arr%2!=0,"Odd",arr))
print(50*'-')
arr1=np.where(arr%2==0,"Even",arr)
arr1=np.where(arr%2!=0,"Odd",arr1)
print(arr1)
print(50*'-')

--------------------------------------------------
[100 100 100   9 100   9   3 100 100 100]
--------------------------------------------------
['Even' 'Even' 'Even' '9' 'Even' '9' '3' 'Even' 'Even' 'Even']
['8' '6' '2' 'Odd' '8' 'Odd' 'Odd' '8' '8' '8']
--------------------------------------------------
['Even' 'Even' 'Even' 'Odd' 'Even' 'Odd' 'Odd' 'Even' 'Even' 'Even']
--------------------------------------------------


In [146]:
#merging/cancatenating arrays
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))
print(30*'-')
print(arr1)
print(30*'-')
print(arr1)
print(30*'-')
print("Merging Row Wise: \n",np.concatenate((arr1,arr2),axis=0))
print(30*'-')
print("Merging Column Wise: \n",np.concatenate((arr1,arr2),axis=1))
print(30*'-')

------------------------------
[[9 5 3]
 [7 5 4]
 [1 8 6]]
------------------------------
[[9 5 3]
 [7 5 4]
 [1 8 6]]
------------------------------
Merging Row Wise: 
 [[9 5 3]
 [7 5 4]
 [1 8 6]
 [6 7 7]
 [9 3 6]
 [9 2 3]]
------------------------------
Merging Column Wise: 
 [[9 5 3 6 7 7]
 [7 5 4 9 3 6]
 [1 8 6 9 2 3]]
------------------------------


In [152]:
# hstack()...horizomtal stack....column wise
# vstack()...vertical stack....row wise

arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))
print(30*'-')
print(arr1)
print(30*'-')
print(arr1)
print(30*'-')
print("vstack ...RowWise: ")
print(np.vstack((arr1,arr2)))
print(30*'-')
print("hstack ...ColumnWise: ")
print(np.hstack((arr1,arr2)))
print(30*'-')

------------------------------
[[3 2 9]
 [9 2 4]
 [2 4 7]]
------------------------------
[[3 2 9]
 [9 2 4]
 [2 4 7]]
------------------------------
vstack ...RowWise: 
[[3 2 9]
 [9 2 4]
 [2 4 7]
 [8 5 1]
 [8 4 8]
 [7 7 4]]
------------------------------
hstack ...ColumnWise: 
[[3 2 9 8 5 1]
 [9 2 4 8 4 8]
 [2 4 7 7 7 4]]
------------------------------


In [156]:
# splitting arrays....splitting is done after concatenation
# hsplit()...horizomtal split....column wise
# vsplit()...vertical split....row wise
arr=np.random.randint(1,10,(4,4))
print(arr)
print(30*'-')
print("Horizontal Split: \n",np.hsplit(arr,2))   # hsplit('array','split intu how many parts')
print(30*'-')
print("Vertical Split: \n",np.vsplit(arr,2))     # vsplit('array','split intu how many parts')
print(30*'-')


[[6 7 9 6]
 [5 5 7 3]
 [3 2 4 8]
 [5 1 6 8]]
------------------------------
Horizontal Split: 
 [array([[6, 7],
       [5, 5],
       [3, 2],
       [5, 1]]), array([[9, 6],
       [7, 3],
       [4, 8],
       [6, 8]])]
------------------------------
Vertical Split: 
 [array([[6, 7, 9, 6],
       [5, 5, 7, 3]]), array([[3, 2, 4, 8],
       [5, 1, 6, 8]])]
------------------------------


In [160]:
# turning pictures into numpy arrays
<img src='gehu.jpeg'>

SyntaxError: invalid syntax (921813986.py, line 2)

In [166]:
from matplotlib.image import imread
img=imread('gehu.jpeg')
print(30*'-')
print(img.shape)
print(30*'-')
print(img)
print(30*'-')

------------------------------
(192, 204, 3)
------------------------------
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
------------------------------
